repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.3
    hooks:
      - id: cspell
        files: site/(.+).md|README.md
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0 # see changelog for latest version
    hooks:
    -   id: bibtex-tidy
        files: references.bib
        args: ['--sort', '--merge'] # any other settings
