#######################################################################################
# Book settings
title: Computational Physiology
author: Henrik Finsberg
logo: "_static/simula_main_rgb.png"

# Information about where the book exists on the web
description: >-
  The Computational Physiology (ComPhy) department at Simula Research Laboratory is an integrated team of researchers working to develop cutting edge biological simulation tools.

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  use_issues_button: false
  extra_navbar: See more at <a href="https://www.simula.no/research/projects/department-computational-physiology">simula.no</a>

# #######################################################################################
# Interact link settings
notebook_interface: "notebook"

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/ComputationalPhysiology/computationalphysiology.github.io
  path_to_book: "."

latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
