# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Physiology
author: Henrik Finsberg
logo: "_static/logo.png"
copyright: "2023"
-description: The Computational Physiology (ComPhy) department at Simula Research Laboratory is an integrated team of researchers working to develop cutting edge biological simulation tools.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/ComputationalPhysiology/computationalphysiology.github.io # Online location of your book

html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: See more at <a href="https://www.simula.no/research/projects/department-computational-physiology">simula.no</a>

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
