name: build-deploy-site

# Only run this when the master branch changes
on:
  push:
    branches:
      - source

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      # Build the book
      - name: Build the book
        shell: bash -l {0}
        run: jupyter-book build docs

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: main # deploying branch
